builds:
  - main: ./cmd/calyptia
    binary: calyptia
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.defaultAuth0ClientID={{.Env.AUTH0_CLIENT_ID}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
universal_binaries:
  - replace: true
