blobs:
  - provider: gs
    bucket: calyptia_cli_bucket
    folder: "releases/{{.Version}}"

builds:
  - main: ./cmd/calyptia
    id: calyptia
    binary: calyptia
    ldflags:
      - -s -w -X main.version={{.Version}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - windows_amd64
universal_binaries:
  - replace: true
