name: CI

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          # TODO: Switch to Workload Identity Federation method.
          # https://github.com/google-github-actions/auth#authenticating-via-workload-identity-federation
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true
          # This will export GOOGLE_APPLICATION_CREDENTIALS
          # for GoReleaser to push the blobs to Google Storage.
          create_credentials_file: true

      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2

      - name: Test
        run: |
          go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage reports
          path: |
            coverage.out
            coverage.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./coverage.out
          flags: ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true
